### ISSUE TITLE
Trouble finding titles?

### ISSUE THREAD

**Issue by rlb2015** [ssilva/bgg-chrome-extension#1]
For instance, Pathfinder Adventure Card Game will find nothing, Rise of the Runelords will find nothing, 
Pathfinder Adventure Card Game: Rise of the Runelords Base Set will find nothing even going to BGG and highlighting the title on the game's page will find nothing...

**Comment by ssilva** [comment]
Hi @rlb2015,

Thank you for this bug report.

**Short answer**: I'll work on it as an enhancement.

**Long answer**:

Right now the extension is passing the parameter `exact=1` to the BGG search API. It seems it's a bit too restrictive, as it expects "Pathfinder Adventure Card Game: Rise of the Runelords – Base Set":

> https://boardgamegeek.com/xmlapi2/search?type=boardgame,boardgameaccessory,boardgameexpansion&exact=1&query=Pathfinder%20Adventure%20Card%20Game:%20Rise%20of%20the%20Runelords%20%E2%80%93%20Base%20Set
> 
> ``` xml
> <items total="1" termsofuse="http://boardgamegeek.com/xmlapi/termsofuse">
>     <item type="boardgame" id="133038">
>         <name type="primary" value="Pathfinder Adventure Card Game: Rise of the Runelords – Base Set"/>
>         <yearpublished value="2013"/>
>     </item>
> </items>
> ```

Now If I remove the `exact=1` parameter and search for "Runelords Base Set", it returns 33 items:

> https://boardgamegeek.com/xmlapi2/search?type=boardgame,boardgameaccessory,boardgameexpansion&query=Rise%20of%20the%20Runelords
> 
> ``` xml
> <items total="33" termsofuse="http://boardgamegeek.com/xmlapi/termsofuse">
> …
> ```

I could probably make the extension figure out which is the most relevant result out of the 33. In this case, returning the item with smallest `id` would get us what we're looking for (we're assuming that older items are more popular and thus have a higher chance of being a better match):

``` xml
<item type="boardgame" id="133038">
    <name type="primary" value="Pathfinder Adventure Card Game: Rise of the Runelords – Base Set"/>
    <yearpublished value="2013"/>
</item>
```

Cheers,
Saulo

**Comment by ssilva** [comment]
I've made initial tests with the proposed changes above. All of the strings mentioned in [the original bug report](https://github.com/ssilva/bgg-chrome-extension/issues/1#issue-182930761) now return the expected result: [Pathfinder Adventure Card Game: Rise of the Runelords – Base Set](https://boardgamegeek.com/boardgame/133038).

I hope to publish a new version of the extension with the changes in the next few days.

**Comment by ryanespin** [comment]
Would this also fix cases for titles like "Mansions of Madness: 2nd Edition".  I tried that on Cool Stuff Inc's page and it wasn't working.  http://www.coolstuffinc.com/p/230613

**Comment by ssilva** [comment]
@ryanespin 

Short answer: No, but it's something Cool Stuff Inc (easily) or BGG (not so easily) could fix.

Long answer:

:no_entry_sign: **"Mansions of Madness: 2nd Edition"** yields no results, event without the `exact=1` parameter:

> https://boardgamegeek.com/xmlapi2/search?type=boardgame,boardgameaccessory,boardgameexpansion&query=Mansions%20of%20Madness:%202nd%20Edition
> 
> ``` xml
> <items total="0" termsofuse="http://boardgamegeek.com/xmlapi/termsofuse"></items>
> ```

:no_entry_sign: **"Mansions of Madness"** yields 22 results. With the fix, the extension would pick up the first edition because it has the smallest id:

> https://boardgamegeek.com/xmlapi2/search?type=boardgame,boardgameaccessory,boardgameexpansion&query=Mansions%20of%20Madness
> 
> ``` xml
> <items total="22" termsofuse="http://boardgamegeek.com/xmlapi/termsofuse">
>     <item type="boardgame" id="83330">
>         <name type="primary" value="Mansions of Madness"/>
>         <yearpublished value="2011"/>
>     </item>
>     …
> ```

Now I've been thinking about adding the option to display the top 3 results (see #5). But even then, we would still not see the second edition of the game as it has a too high of an id.

:white_check_mark: **"Mansions of Madness: _Second Edition_"**, which is the name of the game on [BGG](https://boardgamegeek.com/boardgame/205059/mansions-madness-second-edition) and on [the publisher's site](https://www.fantasyflightgames.com/en/products/mansions-of-madness-second-edition/), works with and without the fix.

I can think of two solutions:
1. Cool Stuff Inc should change the name of the game to match the one on BGG and on FantasyFlightGames.com.
2. The BGG XML API2 function /search needs to be improved so that it returns the "2nd edition" version of the name.

**Comment by ssilva** [comment]
v1.2 containing this fix has been published on the Google Web Store. Please do report any issues.
